services:
  - type: web
    name: EPMS-Api
    runtime: dotnet
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/EPMS.Api.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_VERSION
        value: 6.0  # Update based on your .NET version
